In [5]:
import numpy as np
import pandas as pd

df=pd.read_csv('D:/My Final Project/Meta-Python-course/train-data.csv')
df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74

In [6]:
df.shape

(6019, 14)

In [7]:
df.isnull().sum()

Unnamed: 0              0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 36
Power                  36
Seats                  42
New_Price            5195
Price                   0
dtype: int64

In [8]:
df1=df.drop("New_Price",axis='columns')
df1.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,17.74

In [9]:
k = '18.2 kmpl'

# Split by space (or use k.split() to split by any whitespace)
print(k.split(' ')) 
# Output: ['18.2', 'kmpl']

# Extract the first element and convert to float
print(float(k.split(' ')[0])) 
# Output: 18.2

['18.2', 'kmpl']
18.2

In [10]:
def fix_units(x):
    try:
        return float(x.split(' ')[0])
    except:
        return x

In [11]:
df1['Mileage']=df1['Mileage'].apply(fix_units)
df1['Engine']=df1['Engine'].apply(fix_units)
df1['Power']=df1['Power'].apply(fix_units)

df1.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.2,5.0,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.20,1199.0,88.7,5.0,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76,7.0,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.8,5.0,17.74

In [16]:
df1[df1['Power'].apply(lambda x: type(x)!=float)]


df1[df1['Power'].apply(lambda x: type(x)!=float)]['Power'].unique()

df1['Power']=df1['Power'].apply(lambda x: x.replace('null', '0') if type(x)==str else x)

df1.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.2,5.0,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.20,1199.0,88.7,5.0,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76,7.0,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.8,5.0,17.74

In [12]:
df1['Fuel_Type'].value_counts()

Fuel_Type
Diesel      3205
Petrol      2746
CNG           56
LPG           10
Electric       2
Name: count, dtype: int64

In [ ]:
import pandas as pd

# 1. Filter for Petrol cars and create a copy (fixed syntax from df2.df1)
df2 = df1[df1['Fuel_Type'] == 'Petrol'].copy()

# 2. Clean the 'name' column (lowercase and remove leading/trailing whitespace)
df2['Name'] = df2['Name'].str.lower().str.strip()

# 3. Keep only the first two words (Make and Model)
# Note: Changed '' to ' ' so it joins with a space instead of mashing words together
car='maruti swift dzire vdi'
print(car.split(' '))
print(car.split(' ')[:2])
print(''.join(car.split(' ')[:2]))
df2['Name']=df2['Name'].apply(lambda x: ''.join(x.split(' ')[:2]))

# Check the first few rows to verify the transformation
print(df2.head())

# 4. Find car names that appear more than 10 times (fixed typo in variable name)
car_counts = df2['Name'].value_counts()
cars_count_more_than_10 = car_counts[car_counts > 10].index

['maruti', 'swift', 'dzire', 'vdi']
['maruti', 'swift']
marutiswift
    Unnamed: 0        Name Location  Year  Kilometers_Driven Fuel_Type  \
2            2   hondajazz  Chennai  2011              46000    Petrol
10          10  maruticiaz    Kochi  2018              25692    Petrol
11          11   hondacity  Kolkata  2012              60000    Petrol
22          22      audia6   Mumbai  2015              55985    Petrol
23          23  hyundaii20  Kolkata  2010              45807    Petrol

   Transmission Owner_Type  Mileage  Engine   Power  Seats  Price
2        Manual      First    18.20  1199.0    88.7    5.0   4.50
10       Manual      First    21.56  1462.0  103.25    5.0   9.95
11    Automatic      First    16.80  1497.0   116.3    5.0   4.49
22    Automatic      First    13.53  1984.0  177.01    5.0  23.50
23       Manual      First    18.50  1197.0    80.0    5.0   1.87

In [14]:
# FIX: Create df3 from df2_final (was missing — caused NameError)
df3 = df2_final.copy()

df3=df3.map(lambda x:np.nan if x==0 else x)


df3.groupby('Fuel_Type') ['Engine'].agg(['mean','median'])

df3.groupby('Transmission') ['Engine'].agg(['mean','median'])



df3[df3['Engine']<1500]

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price
2,2,honda jazz,Chennai,2011,46000,Petrol,Manual,First,18.20,1199.0,88.7,5.0,4.50
10,10,maruti ciaz,Kochi,2018,25692,Petrol,Manual,First,21.56,1462.0,103.25,5.0,9.95
11,11,honda city,Kolkata,2012,60000,Petrol,Automatic,First,16.80,1497.0,116.3,5.0,4.49
23,23,hyundai i20,Kolkata,2010,45807,Petrol,Manual,First,18.50,1197.0,80.0,5.0,1.87
25,25,honda city,Mumbai,2012,51920,Petrol,Manual,First,16.80,1497.0,116.3,5.0,4.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5998,5998,volkswagen polo,Pune,2010,70290,Petrol,Manual,Second,17.24,1198.0,73.9,5.0,2.96
6000,6000,hyundai i20,Bangalore,2014,68010,Petrol,Manual,Second,18.50,1197.0,82.85,5.0,5.25
6003,6003,maruti celerio,Bangalore,2015,67600,Petrol,Manual,First,23.10,998.0,67.04,5.0,4.00
6010,6010,honda brio,Delhi,2013,33746,Petrol,Manual,First,18.50,1198.0,86.8,5.0,3.20
6017,6017,maruti wagon,Kolkata,2013,46000,Petrol,Manual,First,18.90,998.0,67.1,5.0,2.65