In [1]:
import pandas as pd
import numpy as np


df=pd.read_csv('D:/My Final Project/Meta-Python-course/titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [2]:
details={'name':['sahan','vijaya','johan','jacab','jerry'],
         'salary':[1000,2000,3000,4000,5000],
         'exp':[2.4,4.3,5.5,np.nan,7.9]}
dl=pd.DataFrame(details)
dl


d2.dl.drop([2,3],axis='rows')
d2


d3=d1.drop([2,3],axis='columns')
d3

NameError: name 'd2' is not defined

In [3]:
d1['exp']=d1['exp'].fillna(d1['exp'].mean())
d1

NameError: name 'd1' is not defined

In [4]:
df.shape

(891, 12)

In [5]:
df1=df.dropna(axis='rows',subset=['Embarked'])
df1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df2=df1.drop('cabin',axis='columns')
df2.head()

KeyError: "['cabin'] not found in axis"

In [ ]:
df2.isnull().sum()

In [ ]:
print(df2['age'])

df2['Age'].hist()

In [ ]:
import seaborn as sns
sns.boxplot(df2['Age'])

In [ ]:
df2['Age']=df2['Age'].fillna(29.70)
print(df2['Age'].mean())
print(df2['Age'].median())

In [ ]:
df.groupby('Sex')['Age'].mean()

In [ ]:
dfa1=df[~df['Age'].isnull()]

In [8]:
dfa0['Age']=dfa0['Pclass'].apply(lambda x: 25.14 if x==3 else 29.87 if x==2 else 38.23)

dfa0.head()

NameError: name 'dfa0' is not defined

In [ ]:
df_new=pd.concat([dfa0,dfa1],ignore_index=True)
df_new.head()


s

In [ ]:
sdf_new=df_new.dropna(axis='rows',subset=['Embarked'])
df_new.head()